baseurl: '/'
url: 'inside.abtion.com'
remote_theme: abtion/github-pages-theme
plugins:
  - jekyll-seo-tag

# Used in the app
abtion_gpt_url: "https://abtion-gpt-next.osc-fr1.scalingo.io/"

# SEO
title: Abtion guidelines
tagline: Extracted from real problems we've encountered and the solutions we found along the way.
description: Extracted from real problems we've encountered and the solutions we found along the way.
email: hello@abtion.com
social:
  name: Abtion A/S
  links:
    - hhttps://www.linkedin.com/company/abtion
    - https://github.com/abtion

defaults:
  - scope:
      path: ''
    values:
      image: /Abtion-io-OG.png
