name: Update Timestamp

on:
  push:
    branches:
      - main

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python (arm64)
        if: ${{ matrix.arch == 'arm64' }}
        uses: deadsnakes/action@v2.1.1
        with:
          python-version: "3.12"
      - name: Set up Python (amd64)
        if: ${{ matrix.arch == 'amd64' }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install gitpython

      - name: Update timestamps
        run: python update_timestamps.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update timestamps"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
