name: Check broken links in markdown

on:
  push:
  # Triggers the workflow every Monday at 9AM
  schedule:
    - cron: "0 9 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1